### ISSUE TITLE
求分享一下这个的原版APP

### ISSUE THREAD

**Issue by girlmore** [FLZeng/mjddz#1]
或者给个Google Play的链接，谢谢。

**Comment by FLZeng** [comment]
https://wwgi.lanzoub.com/ieTk21hg9bje
密码：fcg4

**Comment by girlmore** [comment]
> https://wwgi.lanzoub.com/ieTk21hg9bje 密码：fcg4

多谢

**Comment by girlmore** [comment]
学习了一下您修改后的源码，对比了一下原app，发现你主要改了AdmobAdsMgr.smali中的两个广告函数（loadInterstitialAds、loadRewardedAds）和GooglePlayBillingMgr.smali中的一个pay函数（payForProduct），另外还有几十个文件中变量的初始化不一样，我试着只修改这两个文件的函数，变量初始化太多了没有改，结果安装了还是没对。

老大能指点一下吗？
